language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t akashjain0802/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true akashjain0802/docker-react-app npm run test